package com.example.lda.utils.downloadPdfAndReceipt

import android.content.ActivityNotFoundException
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.graphics.Color
import android.graphics.Paint
import android.graphics.pdf.PdfDocument
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.provider.MediaStore
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.lda.utils.dataClass.TransactionItem
import java.io.File
import java.io.FileOutputStream

object ReceiptPdfUtil {

    // CREATE PDF DOCUMENT
    private fun createPdfDocument(data: TransactionItem): PdfDocument {

        val pdfDocument = PdfDocument()
        val pageInfo = PdfDocument.PageInfo.Builder(595, 842, 1).create()
        val page = pdfDocument.startPage(pageInfo)
        val canvas = page.canvas

        val titlePaint = Paint().apply {
            textSize = 20f
            isFakeBoldText = true
            textAlign = Paint.Align.CENTER
        }

        val amountPaint = Paint().apply {
            textSize = 28f
            isFakeBoldText = true
            textAlign = Paint.Align.CENTER
        }

        val statusPaint = Paint().apply {
            textSize = 16f
            textAlign = Paint.Align.CENTER
        }

        val labelPaint = Paint().apply {
            textSize = 14f
            color = Color.GRAY
        }

        val valuePaint = Paint().apply {
            textSize = 14f
            isFakeBoldText = true
        }

        val linePaint = Paint().apply {
            strokeWidth = 1f
            color = Color.LTGRAY
        }

        var y = 80

        // Header
        canvas.drawText("Transaction Details", 297f, y.toFloat(), titlePaint)
        y += 70

        // STATUS CIRCLE
        val circlePaint = Paint()
        when (data.status) {
            "SUCCESS" -> circlePaint.color = Color.parseColor("#4CAF50")
            "FAILED" -> circlePaint.color = Color.parseColor("#F44336")
            else -> circlePaint.color = Color.parseColor("#FFC107")
        }

        canvas.drawCircle(297f, y.toFloat(), 35f, circlePaint)

        val tickPaint = Paint().apply {
            color = Color.WHITE
            strokeWidth = 6f
            style = Paint.Style.STROKE
        }


        canvas.drawLine(282f, y.toFloat(), 292f, y + 12f, tickPaint)
        canvas.drawLine(292f, y + 12f, 315f, y - 10f, tickPaint)

        y += 70

        // Amount
        canvas.drawText(data.amount, 297f, y.toFloat(), amountPaint)
        y += 35

        // Status Text
        canvas.drawText("Payment ${data.status}", 297f, y.toFloat(), statusPaint)
        y += 25

        // Date
        canvas.drawText(data.date, 297f, y.toFloat(), statusPaint)
        y += 40

        // Divider
        canvas.drawLine(40f, y.toFloat(), 555f, y.toFloat(), linePaint)
        y += 40

        fun drawRow(label: String, value: String) {
            canvas.drawText(label, 40f, y.toFloat(), labelPaint)
            canvas.drawText(value, 320f, y.toFloat(), valuePaint)
            y += 35
        }

        drawRow("Transaction ID", data.txnId)
        drawRow("Bill No", data.billNo)
        drawRow("Property ID", data.propertyId)
        drawRow("Financial year", data.financialYear)
        drawRow("Payment Mode", data.paymentMode)
        drawRow("Bank Reference", data.bankRefNo)

        statusPaint.color = Color.GRAY
        canvas.drawText("This Receipt Generated by e-NagarSeva.", 297f, (pageInfo.pageHeight - 30).toFloat(), statusPaint)

        pdfDocument.finishPage(page)
        return pdfDocument
    }


    // DOWNLOAD TO PUBLIC DOWNLOADS

    fun downloadReceipt(
        context: Context,
        data:TransactionItem
    ) {

        val pdfDocument = createPdfDocument(data)
        val fileName = "Receipt_${System.currentTimeMillis()}.pdf"

        try {

            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {

                // Android 10+
                val resolver = context.contentResolver

                val contentValues = ContentValues().apply {
                    put(MediaStore.MediaColumns.DISPLAY_NAME, fileName)
                    put(MediaStore.MediaColumns.MIME_TYPE, "application/pdf")
                    put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                }

                val uri = resolver.insert(
                    MediaStore.Downloads.EXTERNAL_CONTENT_URI,
                    contentValues
                )
                uri?.let {
                    resolver.openOutputStream(it)?.use { outputStream ->
                        pdfDocument.writeTo(outputStream)
                    }
                    openPdf(context, it)
                }

            } else {
                // Android 9 and below
                val downloadsDir = Environment.getExternalStoragePublicDirectory(
                    Environment.DIRECTORY_DOWNLOADS
                )

                val file = File(downloadsDir, fileName)
                pdfDocument.writeTo(FileOutputStream(file))
                // FileProvider required
                val uri = FileProvider.getUriForFile(
                    context,
                    "${context.packageName}.provider",
                    file
                )

                openPdf(context, uri)
            }

            Toast.makeText(context, "Receipt Downloaded", Toast.LENGTH_SHORT).show()

        } catch (e: Exception) {
            Toast.makeText(context, "Error: ${e.message}", Toast.LENGTH_LONG).show()
        } finally {
            pdfDocument.close()
        }
    }



    // SHARE RECEIPT
    fun shareReceipt(
        context: Context,
        data: TransactionItem
    ) {

        val pdfDocument = createPdfDocument(data)

        val file = File(context.cacheDir, "receipt.pdf")
        pdfDocument.writeTo(FileOutputStream(file))
        pdfDocument.close()

        val uri = FileProvider.getUriForFile(
            context,
            "${context.packageName}.provider",
            file
        )

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "application/pdf"
            putExtra(Intent.EXTRA_STREAM, uri)
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
        }

        context.startActivity(Intent.createChooser(intent, "Share Receipt"))
    }



    private fun openPdf(context: Context, uri: Uri) {

        val intent = Intent(Intent.ACTION_VIEW).apply {
            setDataAndType(uri, "application/pdf")
            addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
        }

        try {
            context.startActivity(intent)
        } catch (e: ActivityNotFoundException) {
            Toast.makeText(context, "No PDF viewer found", Toast.LENGTH_LONG).show()
        }
    }
}